name: Release Drafter

# on:
#   push:
#     branches:
#       - master # 在 master 分支发生更新时执行此 action

on:
  push:
    tags:
      - "v*"

jobs:
  draft_release:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      # - uses: toolmantim/release-drafter@v5.2.0
      #   name: Draft
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          file: "./index.html"
          # asset_name: mything
          tag: ${{ github.ref }}
          overwrite: true
