name: Release Drafter

# on:
#   push:
#     branches:
#       - master # 在 master 分支发生更新时执行此 action

on:
  push:
    tags:
      - "v*"

jobs:
  draft_release:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - uses: toolmantim/release-drafter@v5.2.0
        name: Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.GITHUBTOKEN }}
        with:
          asset_paths: '["./index.html"]'
